# Generated by Django 4.1.3 on 2024-04-10 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets_available',
        ),
    ]
