# Generated by Django 4.1.3 on 2024-04-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ticket_number_alter_event_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
    ]
