# Generated by Django 4.1.3 on 2024-04-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='cmnt',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
