# Generated by Django 4.1.3 on 2024-04-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bookings_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
