# Generated by Django 4.1.3 on 2024-04-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bookings_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='selling',
            field=models.BooleanField(default=False),
        ),
    ]
